### ISSUE TITLE
Empty regexp examples

### ISSUE THREAD

**Issue by pixiitech** [tom-lord/regexp-examples#15]
```//.examples``` or ```Regexp.new('').examples``` results in:

NoMethodError: undefined method `empty?' for nil:NilClass

Should this be returning ```['']``` instead?

Just trying to cover all scenarios! Thanks for the great work.

**Comment by tom-lord** [comment]
Ahh... Nice find, thanks! I must have missed this scenario in the tests.

Note that there is a similar edge case that *is* handled correctly:

    /[^\d\D]/.random_example # => nil
    /[^\d\D]/.examples # => []

I'll write a patch to handle this in the same way.

**Comment by tom-lord** [comment]
Sorry that took me a while to get round to this...

Fixed in: https://github.com/tom-lord/regexp-examples/pull/16

I'll release gem version `1.4.1` to include the fix.

Thanks again for the bug report 😄
