### ISSUE TITLE
Hello, I am trying to use regexp-example but I have an irregular expression and it says that the gem is not compatible with looking back and looking forward, can you help me? is there any solution or do I have to modify the regex?

### ISSUE THREAD

**Issue by tom-lord** [tom-lord/regexp-examples#36]
Hello, I am trying to use regexp-example but I have an irregular expression and it says that the gem is not compatible with looking back and looking forward, can you help me? is there any solution or do I have to modify the regex?

_Originally posted by @anderstroker in https://github.com/tom-lord/regexp-examples/issues/22#issuecomment-552054605_

**Comment by tom-lord** [comment]
Hi @anderstroker. It's hard to give advice without seeing a concrete example of your use case. Could you share it?

As I've stated in the [README](https://github.com/tom-lord/regexp-examples#impossible-features-illegal-syntax), and explained in more detail in [a blog post](https://tom-lord.github.io/Reverse-Engineering-Regular-Expressions/), "irregular" aspects of regex (such as lookarounds) cannot be supported by this library's algorithm.

Perhaps there is a different way to construct the regex, without lookarounds; or perhaps this library isn't a good fit for your problem.

**Comment by anderstroker** [comment]
Oh shure, let me show you, I am building a project that through the license plates validate to which entity they belong, type of vehicle, and other things, I use the gem to give me all the combinations of the regex, I built an example for trailers.
(?!0{2}) this ignore 00,just 01 to 99
[TV]((?<=[T])[X-Z]|(?<=[V])[A-HJ-NPR-Z]) this depending behing character

^(?!0{2})[0-9]{2}[TV]((?<=[T])[X-Z]|(?<=[V])[A-HJ-NPR-Z])[1-9][A-HJ-NPR-Z]$

**Comment by tom-lord** [comment]
So it would be **possible** to re-structure that regex to make it genuinely regular - and therefore leverage this gem - but there's a potential tradeoff in readability, which would be up to you whether to accept.

This:
```
(?!0{2})[0-9]{2}
```

Could be written as:
```
(0[1-9]|[1-9]0|[1-9]{2})
```

And this:
```
[TV] ((?<=[T])[X-Z]|(?<=[V])[A-HJ-NPR-Z])
```

(Won't actually work as you expect, since there's an extra space, but) could be written as:

```
(V [X-Z]|T [A-HJ-NPR-Z])
```

...and voila, the regex is regular!

Final result:

```
/^(0[1-9]|[1-9]0|[1-9]{2}) (V[X-Z]|T[A-HJ-NPR-Z])[1-9][A-HJ-NPR-Z]$/.random_example
# => "50 TV6R"
```

Magic 😄

**Comment by anderstroker** [comment]
Thank you so much, my friend... I will try
